# Generated by Django 5.2.7 on 2026-03-05 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_stairreport_is_accessible_and_more'),
        ('stair', '0004_remove_pathway_min_width_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stairreport',
            name='is_aligned',
        ),
        migrations.AddField(
            model_name='stairreport',
            name='pathway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pathway_reports', to='stair.pathway', verbose_name='Ruta reportada'),
        ),
        migrations.AlterField(
            model_name='stairreport',
            name='stair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stair_reports', to='stair.stair', verbose_name='Escalera reportada'),
        ),
    ]
