# Generated by Django 5.2.7 on 2026-03-01 00:34

import django.db.models.deletion
from django.db import migrations, models


def create_pathway_modes(apps, schema_editor):
    PathwayMode = apps.get_model('stair', 'PathwayMode')
    pathway_modes = [
        (1, 'Walkway', 'transfer_within_a_station', 'Pasillo'),
        (2, 'Stairs', 'stairs', 'Escaleras normales'),
        (3, 'Moving sidewalk/travelator', 'road', 'Cinta transportadora'),
        (4, 'Escalator', 'escalator', 'Escalera eléctrica'),
        (5, 'Elevator', 'elevator', 'Elevador'),
        (6, 'Fare gate', 'gate', 'Torniquete'),
        (7, 'Exit gate', 'exit_to_app', 'Puerta de salida'),
    ]
    for elem_id, gtfs_name, icon, name in pathway_modes:
        PathwayMode.objects.create(
            id=elem_id, name=name, icon=icon, gtfs_name=gtfs_name)


class Migration(migrations.Migration):

    dependencies = [
        ('stair', '0002_stair_route_blur'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathwayMode',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('gtfs_name', models.CharField(max_length=255, verbose_name='Nombre en GTFS')),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Pathway Mode',
                'verbose_name_plural': 'Pathway Modes',
            },
        ),
        migrations.RenameIndex(
            model_name='pathway',
            new_name='stair_pathw_pathway_7d7f89_idx',
            old_name='stair_pathw_pathway_77daeb_idx',
        ),
        migrations.AlterField(
            model_name='pathway',
            name='pathway_mode',
            field=models.ForeignKey(blank=True, help_text='Type of pathway (e.g., walkway, stairs, escalator)', null=True, on_delete=django.db.models.deletion.CASCADE, to='stair.pathwaymode'),
        ),
        migrations.RunPython(create_pathway_modes),
    ]
