# Generated by Django 5.2.7 on 2026-03-05 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stair', '0003_pathwaymode_and_more'),
        ('stop', '0007_level_alter_route_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pathway',
            name='min_width',
        ),
        migrations.RemoveField(
            model_name='pathway',
            name='reversed_signposted_as',
        ),
        migrations.RemoveField(
            model_name='pathway',
            name='signposted_as',
        ),
        migrations.AddField(
            model_name='pathway',
            name='code_identifiers',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Todos los códigos identificadores'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='miro_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pathway',
            name='pathway_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pathway',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='from_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways_from', to='stop.stop'),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='is_bidirectional',
            field=models.IntegerField(choices=[(0, 'Unidirectional'), (1, 'Bidirectional')]),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='length',
            field=models.FloatField(blank=True, help_text='Horizontal length in meters', null=True),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='pathway_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='pathway_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stair.pathwaymode'),
        ),
        migrations.AlterField(
            model_name='pathway',
            name='to_stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pathways_to', to='stop.stop'),
        ),
    ]
