# Generated by Django 5.2.7 on 2026-06-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stair', '0004_remove_pathway_min_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Pathway clausurado (x en Miro o color gris claro #e7e7e7)'),
        ),
    ]
