# Generated by Django 5.2.7 on 2026-09-02 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stair', '0005_pathway_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='osm_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='Id del objeto en OSM. Enlace blando: OSM no garantiza ids permanentes; si se rompe se re-empareja por ref + estación + geometría (adr-0003)', null=True),
        ),
        migrations.AddField(
            model_name='pathway',
            name='osm_type',
            field=models.CharField(blank=True, choices=[('node', 'Node'), ('way', 'Way'), ('relation', 'Relation')], help_text='Tipo del objeto de OSM enlazado', max_length=8, null=True),
        ),
    ]
