# Generated by Django 5.2.7 on 2026-03-01 00:34

import django.db.models.deletion
from django.db import migrations, models


def create_location_types(apps, schema_editor):
    LocationType = apps.get_model('stop', 'LocationType')
    location_types = [
        {'id': 0, 'name': 'Stop/Platform'},
        {'id': 1, 'name': 'Station'},
        {'id': 2, 'name': 'Entrance/Exit'},
        {'id': 3, 'name': 'Generic Node'},
        {'id': 4, 'name': 'Boarding Area'},
    ]
    for lt in location_types:
        LocationType.objects.create(**lt)


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0005_alter_stop_location_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Location Type',
                'verbose_name_plural': 'Location Types',
            },
        ),
        migrations.AddField(
            model_name='stop',
            name='parent_station',
            field=models.ForeignKey(blank=True, help_text='Defines hierarchy between different locations', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_stops', to='stop.stop'),
        ),
        migrations.AddField(
            model_name='stop',
            name='stop_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='location_type',
            field=models.ForeignKey(blank=True, default=None, help_text='Tipo de ubicación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='stop.locationtype'),
        ),
        migrations.RunPython(create_location_types),
    ]
