# Generated by Django 5.2.7 on 2026-03-05 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0006_locationtype_stop_parent_station_stop_stop_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('level_index', models.FloatField(blank=True, help_text='Relative elevation of the level. 0 is ground level, positive is above, negative is below.', null=True)),
                ('level_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Level',
                'verbose_name_plural': 'Levels',
            },
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['route_sort_order', 'route_short_name'], 'verbose_name': 'Route', 'verbose_name_plural': 'Routes'},
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='stop_route_route_t_1e6194_idx',
        ),
        migrations.RemoveIndex(
            model_name='route',
            name='stop_route_route_s_25c6cd_idx',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='zone_id',
        ),
        migrations.AddField(
            model_name='station',
            name='miro_frame_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='end_anchor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stop',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stop',
            name='main_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main_stops', to='stop.route'),
        ),
        migrations.AddField(
            model_name='stop',
            name='miro_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='rotation',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='viz_params',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='x_position',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='y_position',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_long_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre largo'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_short_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre corto'),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_type',
            field=models.IntegerField(choices=[(0, 'Tram, Streetcar, Light rail'), (1, 'Subway, Metro'), (2, 'Rail'), (3, 'Bus'), (4, 'Ferry'), (5, 'Cable tram'), (6, 'Aerial lift, suspended cable car'), (7, 'Funicular'), (11, 'Trolleybus'), (12, 'Monorail')], default=1),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='station',
            name='x_position',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='y_position',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='route',
            field=models.ForeignKey(blank=True, help_text='Ruta (solo METRO CDMX)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='stop.route'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_code',
            field=models.CharField(blank=True, help_text='Short text or number for riders', max_length=50, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(db_index=True, help_text='Identifies the location stop', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='level',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='stop.route'),
        ),
        migrations.AddField(
            model_name='stop',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stops', to='stop.level'),
        ),
    ]
