# Generated by Django 5.2.7 on 2026-04-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0007_level_alter_route_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='end_anchor',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='main_route',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='rotation',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='viz_params',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='y_position',
        ),
        migrations.AddField(
            model_name='stop',
            name='has_entry',
            field=models.BooleanField(default=True, help_text='Indicates if the stop has an entry/exit point'),
        ),
        migrations.AddField(
            model_name='stop',
            name='has_exit',
            field=models.BooleanField(default=True, help_text='Indicates if the stop has an exit point'),
        ),
    ]
