# Generated by Django 5.2.7 on 2026-06-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0008_remove_stop_end_anchor_remove_stop_main_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='is_double',
            field=models.BooleanField(default=False, help_text='Salida que representa IZQ & DER en un solo nodo Miro'),
        ),
    ]
