# Generated by Django 5.2.7 on 2026-09-02 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stop', '0009_stop_is_double'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='has_entry',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='has_exit',
        ),
        migrations.AddField(
            model_name='stop',
            name='entrance',
            field=models.CharField(blank=True, choices=[('yes', 'Entrar y salir'), ('entrance', 'Solo entrar'), ('exit', 'Solo salir')], help_text="En accesos es la etiqueta OSM entrance=* tal cual. En andenes, 'entrance' = solo ascenso (los trenes parten) y 'exit' = solo descenso (los trenes llegan).", max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='short_name',
            field=models.CharField(blank=True, help_text='Nombre tal como se usa en el título del frame de Miró cuando el nombre GTFS trae añadidos («Etiopía» vs «Etiopía y Plaza de la Transparencia»).', max_length=100, null=True),
        ),
    ]
